[package]
name = "sapi"
version = "0.1.1"
authors = ["Ganda Wenang Sani <wenang.sani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# actix
actix-web = "4.13.0"
actix-web-httpauth = "0.8.2"
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-cors = "0.7.1"
actix-ws = "0.2.5"
actix-rt = "2.9.0"
anyhow = "1.0.82"

# database
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls-ring",
    "mysql",
    "macros",
    "chrono",
    "rust_decimal",
    "json",
] }
chrono = { version = "0.4.45", features = ["serde"] }

# json0.4.19
rust_decimal = { version = "1.42.0", features = ["serde-float"] }
serde = "1.0.228"
serde_json = "1.0.150"
serde_derive = "1.0.228"
# json5 = "0.3.0"

# other
jsonwebtoken = "8.3.0"
uuid = { version = "1.4.1", features = ["v4"] }
futures = "0.3.30"
futures-util = "0.3.28"
rand = "0.8.5"
bcrypt = "0.15"
dotenvy = "0.15"

tokio-stream = { version = "0.1", features = ["sync"] }
tokio = { version = "1", features = ["full"] }